### ISSUE TITLE
Crash with Storage Drawers 1.10.2-3.2.2

### ISSUE THREAD

**Issue by ShadowDrakken** [Belgabor/DrawersBits#2]
Just updated our server with the latest Storage Drawers and now when clients log in this occurs on the client side (server is fine)

java.lang.NoClassDefFoundError: mods/belgabor/bitdrawers/storage/BitDrawerData
    at mods.belgabor.bitdrawers.block.tile.TileBitDrawers.createDrawer(TileBitDrawers.java:71)
    at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawers.initWithDrawerCount(TileEntityDrawers.java:93)
    at com.jaquadro.minecraft.storagedrawers.block.tile.TileEntityDrawers.<init>(TileEntityDrawers.java:81)
    at mods.belgabor.bitdrawers.block.tile.TileBitDrawers.<init>(TileBitDrawers.java:49)
    at mods.belgabor.bitdrawers.block.BlockBitDrawers.createNewTileEntity(BlockBitDrawers.java:120)
    at mods.belgabor.bitdrawers.block.BlockBitDrawers.func_149915_a(BlockBitDrawers.java:57)
    at net.minecraft.block.Block.createTileEntity(Block.java:1204)
    at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
    at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
    at net.minecraft.world.ChunkCache.func_190300_a(ChunkCache.java:74)
    at net.minecraft.world.ChunkCache.func_175625_s(ChunkCache.java:64)
    at com.jaquadro.minecraft.storagedrawers.block.BlockDrawers.getTileEntity(BlockDrawers.java:654)
    at mods.belgabor.bitdrawers.block.BlockBitDrawers.func_176221_a(BlockBitDrawers.java:145)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:410)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:68)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Belgabor** [comment]
That is extremely odd, it's reporting one of my own classes missing. The issue does not happen in my development environment, I can reproduce it with a production instance though.

I'll admit I'm utterly at a loss. For now I can only recommend going back to 3.2.1.

**Comment by Belgabor** [comment]
Found the issue. Expect a fix soon.

**Comment by Belgabor** [comment]
Fixed in v0.21
